repo: seabass-labrax/license-list-test
startAt: 2022-08-20
pullRequests: false
filters:
  - type: issue
    criteria:
      state: closed
      labels:
        $and:
          - $eq: 'new license/exception: Accepted'
          - $neq: 'finalised'
actions:
  - type: add_comment
    body: >
      This new license request has been accepted and the license's information
      has been added to the repository. Thank you to everyone who has
      participated!

      The license's information will be published at https://spdx.org/licenses/
      as part of the next SPDX License List release, which will occur no longer
      than three months from now.
  - type: add_label
    label: 'finalised'
