name: Comment automatically on accepted license requests

on:
  push:
    branches:
      - '**'

jobs:
  comment:
    name: Comment automatically on accepted license requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install git3po
        run: npm install -g git3po
      - name: Run `git3po` to leave comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git3po -c auto-comment.yaml
